set -s escape-time 0
bind r source-file ~/.tmux.conf

set -g mouse on
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key : command-prompt
# set-option -g default-terminal "screen-256color"
set -g default-terminal "xterm-ghostty"
set -ga terminal-overrides ",xterm-ghostty:Tc"
set-option -g allow-rename off

# Rebind prefix to <C-a>
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# split pane
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# switch pane
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind k select-pane -U

# Start with index 1
set -g base-index 1
setw -g pane-base-index 1
bind c new-window -c "#{pane_current_path}"

# Style
set -g status-position top
set -g status-style "fg=#42899b bg=default"
set -g status-left-style "fg=#94c4c1 bg=default bold"
set -g status-right ''
set -g window-status-current-style "fg=#94c4c1 bg=default bold"
set-window-option -g mode-style "bg=#264f78"
